# Generated by Django 4.2.2 on 2023-06-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(null=True, upload_to='movies_uploaded/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(null=True, upload_to='movies_uploaded/<django.db.models.fields.CharField>/'),
        ),
    ]
