# Generated by Django 4.2.2 on 2023-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_trailer_alter_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
