# Generated by Django 4.2.2 on 2023-06-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_category_alter_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
