# Generated by Django 4.2.2 on 2023-06-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
